In [1]:
pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Collecting kaggle
  Downloading kaggle-1.8.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: black>=24.10.0 in c:\programdata\anaconda3\lib\site-packages (from kaggle) (24.10.0)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from kaggle) (6.2.0)
Collecting kagglesdk (from kaggle)
  Downloading kagglesdk-0.1.13-py3-none-any.whl.metadata (13 kB)
Collecting mypy>=1.15.0 (from kaggle)
  Downloading mypy-1.18.2-cp313-cp313-win_amd64.whl.metadata (2.2 kB)
Requirement already satisfied: protobuf in c:\programdata\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\programdata\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in c:\programdata\anaconda3\lib\site-packages (from kaggle) (72.1.0)
Requirement already satisfied: six>=1.10 in c:\programdata\anaconda3\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Collecting types-requests (from kaggle)
  Downloading types_requests-2.32.4.20250913-py3-none-any.whl.metadata (2.0 kB)
Collecting types-tqdm (from kaggle)
  Downloading types_tqdm-4.67.0.20250809-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: click>=8.0.0 in c:\programdata\anaconda3\lib\site-packages (from black>=24.10.0->kaggle) (8.1.8)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\programdata\anaconda3\lib\site-packages (from black>=24.10.0->kaggle) (1.0.0)
Requirement already satisfied: packaging>=22.0 in c:\programdata\anaconda3\lib\site-packages (from black>=24.10.0->kaggle) (24.2)
Requirement already satisfied: pathspec>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from black>=24.10.0->kaggle) (0.10.3)
Requirement already satisfied: platformdirs>=2 in c:\programdata\anaconda3\lib\site-packages (from black>=24.10.0->kaggle) (4.3.7)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click>=8.0.0->black>=24.10.0->kaggle) (0.4.6)
Requirement already satisfied: typing_extensions>=4.6.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from mypy>=1.15.0->kaggle) (4.14.1)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\programdata\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from requests->kaggle) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->kaggle) (2025.6.15)
Downloading kaggle-1.8.2-py3-none-any.whl (256 kB)
Downloading mypy-1.18.2-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ----------------------------- ---------- 7.3/9.8 MB 33.5 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 36.2 MB/s  0:00:00
Downloading kagglesdk-0.1.13-py3-none-any.whl (159 kB)
Downloading types_requests-2.32.4.20250913-py3-none-any.whl (20 kB)
Downloading types_tqdm-4.67.0.20250809-py3-none-any.whl (24 kB)
Installing collected packages: types-requests, mypy, types-tqdm, kagglesdk, kaggle

   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   -------- ------------------------------- 1/5 [mypy]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   ------------------------ --------------- 3/5 [kagglesdk]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   -------------------------------- ------- 4/5 [kaggle]
   ---------------------------------------- 5/5 [kaggle]

Successfully installed kaggle-1.8.2 kagglesdk-0.1.13 mypy-1.18.2 types-requests-2.32.4.20250913 types-tqdm-4.67.0.20250809
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import os 
os.environ["KAGGLE_API_TOKEN"] = "KGAT_5d298e294a7ccfa138170d9dad996599"

In [9]:
!kaggle competitions download -c titanic

Downloading titanic.zip to C:\Users\user\python_basic\ML\251128

  0%|          | 0.00/34.1k [00:00<?, ?B/s]
100%|##########| 34.1k/34.1k [00:00<00:00, 41.3MB/s]

In [10]:
!kaggle competitions list

ref                                                                              deadline             category          reward  teamCount  userHasEntered
-------------------------------------------------------------------------------  -------------------  ---------  -------------  ---------  --------------
https://www.kaggle.com/competitions/ai-mathematical-olympiad-progress-prize-3    2026-04-15 23:59:00  Featured   2,207,152 Usd        366           False
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge      2017-12-15 23:59:00  Featured   1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                               2018-01-10 15:59:00  Featured   1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                       2017-04-12 23:59:00  Featured   1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection             2023-06-14 23:59:00  Featured   1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming               2025-08-26 23:59:00  Featured     500,000 Usd        608           False
https://www.kaggle.com/competitions/openai-to-z-challenge                        2025-06-29 23:59:00  Featured     500,000 Usd        226           False
https://www.kaggle.com/competitions/llm-prompt-recovery                          2024-04-16 23:59:00  Featured     200,000 Usd       2175           False
https://www.kaggle.com/competitions/asl-fingerspelling                           2023-08-24 23:59:00  Research     200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl              2016-03-14 23:59:00  Featured     200,000 Usd        192           False
https://www.kaggle.com/competitions/datasciencebowl                              2015-03-16 23:59:00  Featured     175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                       2020-01-22 23:59:00  Featured     160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                          2022-03-15 23:59:00  Featured     160,000 Usd       2058           False
https://www.kaggle.com/competitions/the-nature-conservancy-fisheries-monitoring  2017-04-12 23:59:00  Featured     150,000 Usd       2293           False
https://www.kaggle.com/competitions/tensorflow-great-barrier-reef                2022-02-14 23:59:00  Research     150,000 Usd       2025           False
https://www.kaggle.com/competitions/AI4Code                                      2022-11-10 23:59:00  Featured     150,000 Usd       1135           False
https://www.kaggle.com/competitions/google-gemma-3n-hackathon                    2025-08-06 23:59:00  Featured     150,000 Usd        606           False
https://www.kaggle.com/competitions/gemma-language-tuning                        2025-01-15 00:59:00  Analytics    150,000 Usd          0           False
https://www.kaggle.com/competitions/genentech-flu-forecasting                    2014-03-03 23:59:00  Masters      125,000 Usd         50           False
https://www.kaggle.com/competitions/severstal-steel-defect-detection             2019-10-24 23:59:00  Featured     120,000 Usd       2427           False

In [11]:
import pandas as pd 

train = pd.read_csv("titanic/train.csv")
test = pd.read_csv("titanic/test.csv")

In [12]:
# head() + tail() 각 feature 
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
train.head(100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [14]:
train.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q