In [2]:
import pickle

with open("titanic_step2_feature_add.pickle", "rb") as pickle_filename :
    df = pickle.load(pickle_filename)

In [3]:
# 인코딩 => 특정 사이트 데이터 크롤링 => 주피터노트북 (*문자열 깨짐없이) | 코드문안 => 컴퓨터 이해할 수 있는 형태
# 사람이 이해할 수 있는 문법 => 컴퓨터 이해할 수 있는 형태 : 인코딩
# 컴퓨터 처리한 문법 => 사람이 이해할 수 있는 형태 : 디코딩

# sklearn & numpy & pandas & plotly
# 레이블 인코딩 => LableEncoding

# 레이블 인코딩 : 문자열 형태의 데이터를 가지고 있다 => 숫자형태의 범주형 카테고리로 분류해서 알아서 인코딩
# 원핫 인코딩 => OneHotEncoding : 각 문자열 범주마다 새로운 feature를 만들고 해당 범주에 속하는 경우에만 1값을 부여하는 방식의 인코딩
# BigQuery => event params => key

In [4]:
df_label = df.copy()
df_onehot = df.copy()

ntrain = 886
train = df[:ntrain]

y_train = train[["Survived"]].copy()

In [5]:
y_train

     Survived
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[886 rows x 1 columns]

In [6]:
drop_features = ["PassengerId", "Survived"]
df_label = df_label.drop(drop_features, axis=1).copy()
df_label.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,3,0,3.0,0.0,0,0,0.0,2,0,3,0,0
1,1,1,4.0,3.0,1,1,2.0,2,1,3,2,0
2,3,1,3.0,0.0,0,0,1.0,1,2,9,0,0
3,1,1,4.0,2.0,1,0,2.0,2,3,5,2,0
4,3,0,4.0,0.0,0,0,0.0,1,3,9,0,2

In [7]:
drop_features = ["PassengerId", "Survived"]
df_onehot = df_onehot.drop(drop_features, axis=1).copy()
df_onehot.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,3,0,3.0,0.0,0,0,0.0,2,0,3,0,0
1,1,1,4.0,3.0,1,1,2.0,2,1,3,2,0
2,3,1,3.0,0.0,0,0,1.0,1,2,9,0,0
3,1,1,4.0,2.0,1,0,2.0,2,3,5,2,0
4,3,0,4.0,0.0,0,0,0.0,1,3,9,0,2

In [8]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [9]:
df_label = df_label.apply(LabelEncoder().fit_transform)

In [10]:
df_label.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,2,0,3,0,0,0,0,1,0,3,0,0
1,0,1,4,3,1,1,2,1,1,3,2,0
2,2,1,3,0,0,0,1,0,2,9,0,0
3,0,1,4,2,1,0,2,1,3,5,2,0
4,2,0,4,0,0,0,0,0,3,9,0,2

In [11]:
import pandas as pd

onehot_cols = df_label.columns.tolist()
df_onehot = pd.get_dummies(df_label, columns=onehot_cols)
df_onehot = df_onehot.astype(int)

df_onehot.head()

,Pclass_0,Pclass_1,Pclass_2,Sex_0,Sex_1,Age_0,Age_1,Age_2,Age_3,Age_4,...,HighChance_0,HighChance_1,HighChance_2,HighChance_3,HighChance_4,HighChance_5,HighChance_6,LowChance_0,LowChance_1,LowChance_2
0,0,0,1,1,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
4,0,0,1,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [12]:
onehot_cols

['Pclass',
 'Sex',
 'Age',
 'Fare',
 'Cabin',
 'Embarked',
 'Initial',
 'Family',
 'Ticket_Initial2',
 'Ticket_Num_Cut',
 'HighChance',
 'LowChance']

In [13]:
import pickle

with open("titanic_step3_feature_encoding.pickle", "wb") as pickle_filename :
    pickle.dump(df_onehot, pickle_filename)

In [14]:
import pickle

with open("titanic_step3_feature_encoding_y.pickle", "wb") as pickle_filename :
    pickle.dump(y_train, pickle_filename)

In [15]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

# 몇개 등분으로 나눌것인가, 등분으로 나눈 구간에 데이터의 값을 섞어서 넣을지, 랜덤형태로 섞을것인지
# n_splits, shuffle, randim_state
# 컴퓨터는 랜덤기능 > 랜덤 > 애초에 컴퓨터는 숫자를 랜덤으로 추첨 x
# 0, 1 => 최초의 랜덤 => 계속 // 랜덤 x // 랜덤씨드 => 시간

# 어떤 모델, 어떤 데이터값, 어떤 설정, 어떤 계산식으로 교차검증을 할 것인가?
# estimator : 어떤 모델을 사용할 것인가?
# x : train 시킬 데이터 값
# y : train 시킬 데이터의 정답
# cv : forld 객체를 통해서 생성된 인스턴스 객체
# n_jobs : cpu 1
# scoring : 모델 평가식을 어떻게 할 것인지

knn = KNeighborsClassifier(n_neighbors=13)
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)
score = cross_val_score(knn, X_train, y_train, cv=k_fold, n_jobs=1, scoring="accuracy")

NameError: name 'X_train' is not defined

In [16]:
import warnings
warnings.filterwarnings("ignore")

import pickle
with open("titanic_step3_feature_encoding.pickle", "rb") as pickle_filename :
    df_oneshot = pickle.load(pickle_filename)

with open("titanic_step3_feature_encoding_y.pickle", "rb") as pickle_filename :
    y_train = pickle.load(pickle_filename)

ntrain = 886
X_train, X_test = df_oneshot[:ntrain], df_oneshot[ntrain:]
X_train.head()

,Pclass_0,Pclass_1,Pclass_2,Sex_0,Sex_1,Age_0,Age_1,Age_2,Age_3,Age_4,...,HighChance_0,HighChance_1,HighChance_2,HighChance_3,HighChance_4,HighChance_5,HighChance_6,LowChance_0,LowChance_1,LowChance_2
0,0,0,1,1,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
4,0,0,1,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [17]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=13)
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

In [19]:
score = cross_val_score(knn, X_train, y_train, cv=k_fold, n_jobs=1, scoring="accuracy")
score

array([0.84269663, 0.76404494, 0.82022472, 0.80898876, 0.80898876,
       0.82022472, 0.85227273, 0.77272727, 0.86363636, 0.85227273])

In [20]:
import numpy as np
np.mean(score) * 100

np.float64(82.06077630234934)

In [24]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

iris_data = load_iris()
dir(iris_data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [25]:
iris_df = pd.DataFrame(data = iris_data.data, columns = iris_data.feature_names)

In [26]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [27]:
logreg_model = LogisticRegression()
svc_model = SVC() 
decision_model = DecisionTreeClassifier() 
random_model = RandomForestClassifier() 
extra_model = ExtraTreesClassifier()
gbm_model = GradientBoostingClassifier() 
nb_model = GaussianNB() 
xgb_model = XGBClassifier(eval_metric="logloss")
lgbm_model = LGBMClassifier() 

results = dict()

In [ ]:
alg = logreg_model 
alg.fit(X_train, y_train)